---
title: "2_FlowSOM_clustering_RADIANT.V0.1_usr"
output: html_notebook
---

```{r, Chunk 1: prepare working environment}

### ADJUSTABLE VARIABLES ###

# Set the working directory to specify the file location
  wd = "/C:/user/Analysis/" 

# Define experiment variables
  cellType = "cellType" # select the folder containing the data you want to analyse. Valid entries should match a folder name in wd specified above
  expID = "expID" # add the name of the study, or experiment.
  file_pattern = "uncomp.fcs" # shared digit/character at the end of fcs files and fcs extension
  ds = "FC" # Specify the data source (valid inputs: "FS" for normal flow cytometry, "SFC" for spectral flow cytometry)


  
### CODE ###

# importing custom functions
  RMD = "FlowSOM_clustering"
  source(file.path(wd, cellType, "00 RADIANT files", "RADIANT_dependencies_usr_v0.1.R"))
# install missing packages, install them if required 
  autoInstallpkg()
# load required packages
  autoLoadpkg()
# checks which files are created previously
  checkPreviousRuns()
# locate necessary files
  mapDirectories()
  

```

```{r, Chunk 2: loading data into the working environment, importing md and panel files and creating sce object.}
### ADJUSTABLE VARIABLES ###

# valid input are options as described in previous chunk
# b = transformed files, c = cleaned and transformed files, d = normalized files
  to_import = "d" # valid input: b, c or d
  TCs = TRUE # set to TRUE if the data contains technical controls
  

### CODE ###

  stopifnot(to_import %in% c("b", "c", "d"))
# import required files
  import_fcs_files()
  importData() 
# create sce object 
  load_data()
  
```




```{r, Chunk 3: down sampling, clustering and dimension reduction.}
### ADJUSTABLE VARIABLES ###

  excluded_markers = c() # add the markers you want to exclude from clustering to this list

# down sampling 
  min_cells = 10000 # indicate the minimum amount of cells to include from each file (files with less cells will be excluded from analysis)
  max_cells = 10000 # indicate the maximum amount of cells to include from each file

# clustering  
  performPG = FALSE # set to TRUE if you want to perforn PhenoGraph clustering in addition to FlowSOM
  PGnn = 30 # set the number of nearest neighbors for PhenoGraph. Default is 30
  metClust = 25 # set number of metaclusters for FlowSOM
  seedFS = 1324 # set seed for flowSOM
  FSxdim = 8 # set the amount of SOMnodes in the x-dimension
  FSydim = 8 # set the amount of SOMnodes in the y-dimension
  
# dimension reduction 
  anType = c("UMAP") # indicate which type of analysis you want to be done (c(UMAP, T-SNE))
  clusterSeed = 1234 # set the seed for UMAP and T-SNE
  UMAP_cells = 10000 # set the number of cells per file you want to run UMAP on
  TSNE_cells = 10000 # set the number of cells per file you want to run T-SNE on
  
# deepClustering  
  runDC = TRUE # indicate whether or not you want to perform deepClustering
  performMerge = TRUE # set to TRUE if you want to perform metaclustering on the PhenoGraph clusters after DeepClustering
  DCminCells = 800 # set the minimum amount of cells that need to be present in a cluster to perform deep clustering
  NRSthreshold = 0.5 #set threshold for NRS score. Markers below this value will be removed for deep clustering. Default is 0.5
  DCmethod = c("PhenoGraph") #indicate which clustering method to use for deep clustering. Valid options are "FlowSOM" and " PhenoGraph
  binNo = 100 #set the amount of bins for both the x and y direction. Default is 100
  dbScanEps = 0.5 #set the size (radius) of the epsilon neighborhood for dbScan. Default is 0.5
  dbScanMinPts = 1 #set the number of minimum points required in the eps neighborhood to qualify as a cluster
  mfiThresholdMethod = "3q" # set the method to set a threshold of each marker to determine similarity between clusters. Valid options are "1q", "median", "mean" and "3q"
  mergeThreshold = 3 #set the maximum amount of markers that may differ between clusters before they are merged
  plotFraction = FALSE #set to any value to use as the maximum amount of cells per dbScan cluster that should be plotted for the UMAP results. Can also be FALSE if everything needs to be plotted



### CODE ###

# Pooling type_markers and state_markers
  TSMarkers = c(type_markers(sce), state_markers(sce))
# down sample the data to max_cells
  downSample()
# removes markers from sce if indicated and create list of all (remaining) markers
  removeMarkers()

 
  Sys.time()
  
# Perform FlowSOM clustering
  performClustering()
  

# Perform UMAP and/or TSNE dimensional reduction
  performDimRed()
  
  
# Create dataframe containing metadata, DR coordinates, MC ids and (scaled) expression data per cell  
  generateCellData()
  
  Sys.time()
  
# Perform Deep Clustering  
  performDC()
  
  
      
```

```{r, Chunk 4: determination requirement of cluster merging. }

### ADJUSTABLE VARIABLES ###
 
  plot_sequences = TRUE # put to TRUE if you want to plot a sequence of UMAP/T-SNE and heatmaps of FlowSOM meta clusters. If you've only run PhenoGraph only 1 plot will be generated
  start_nr = 5 # indicate the starting amount of FlowSOM metaclusters to plot 
  end_nr = metClust # indicate the maximum amount of FlowSOM metaclusters to plot (maximum value is metClust)
  corThreshold = 0.95 # set the threshold for coloring the correlation matrix. Can be any value between 0 and 1
  
  
### CODE ###
  
  plot_sequences_DR()
  

  
  
  
 
  
```

```{r, Chunk 5: cluster merging/renaming files.}

### ADJUSTABLE VARIABLES ###

# merging clusters
  performClusterMerging = FALSE # put to FALSE if you don't want to run cluster merging 
  customMeta = 15 # set the amount of metaclusters you want to work with. Needs to be lower, or equal to metClust in the previous chunk 
  writeCM = TRUE # put to TRUE when you need to create a merging table excel sheet (so your first run)
  
# plot heatmap/UMAP before and/or after merging  
  plotDiagnosticsBefore = TRUE # plot a UMAP and heatmap for clusters before merging
  plotDiagnosticsCM = TRUE # plot a UMAP and heatmap for merged clusters
  

### CODE ###
  
# perform cluster merging  
  cluster_merging()
# create a settings file
  createSettingsFile("Settings_clustering_")
# Check which files are present in the environment
  Summary_environment = TRUE
# save variables required for downstream analysis
  save_variables_rmd2()
  
  
```

```{r, Chunk 6: evaluation cluster merging.}

### ADJUSTABLE VARIABLES ###

  name_CM_result = "Plot_1"
  save_plots = TRUE # if you want to save the result (with the file name as specified in name_CM_result) put to TRUE

  if(performClusterMerging){
  p =   plotPbExprs( 

          # can be altered
            fun = c("mean"), # character string specifying the summary statistic to use. valid options are: median, mean...
            geom = c("both"), # character string specifying whether to include only points, box plots or both
            size_by = FALSE, # of geom is not both or box_plot, you can alter shape size with changing it to just a number
            ncol = 6, # integer scalar specifying number of facet columns.
            
            facet_by = "antigen", # what to split the different box plots in. valid options: antigen or cluster_id
            color_by = "batch", # valid options are column names of the metadata (run names(colData(sce_merge)) if unsure what options are)
            shape_by = NULL, # valid options are column names of the metadata
  
          
### CODE ###
  
            sce_merge,
            k = "merging1",
            features = "type",
            assay = "exprs",
            jitter = TRUE) +
          
          theme_classic()
      
  
# save output figure to cluster merging folder
  save_CM_plots()
  }


```
